### ISSUE TITLE
الإعدادات و أوقات الصلاة لا تعمل

### ISSUE THREAD

**Issue by HishamAHai** [rn0x/Altaqwaa-Islamic-Desktop-Application#14]
السلام عليكم و بارك الله بكم على هذا البرنامج
بعد تثبيت البرنامج على نظامي تشغيل مختلفين ويندوز و لينكس واجهت المشكلة نفسها و هي أن أوقات الصلاة لا تعمل تظهر فقط النافذة الخاصة بها بدون أي مواقيت كما هو موضح في لقطة الشاشة
كما أن الإعدادات لتغيير الإحداثيات و المنطقة الزمنية كذلك لا تعمل و لا يتم حفظها بعد إعادة تشغيل البرنامج

<img width="1032" alt="altaqwa_prayertimes" src="https://user-images.githubusercontent.com/50996735/221350293-6f858e72-aa92-4d87-9247-5ab3c370abc4.png">
<img width="1033" alt="altaqwa_settings" src="https://user-images.githubusercontent.com/50996735/221350295-446cd5d5-6021-4082-bef2-bcd82fbb1e99.png">

**Comment by kemzops** [comment]
بسبب التحديثات المستمرة على البكجات(الملحقات) المستخدمة في المشروع والتي نعتمد عليها لايوجد تحديث مستقر بالكامل ولايمكن ضمان ذلك في الوقت الحالي... سوف اقوم بعمل تجارب عديدة على البرنامج والتحقق من وجود مشاكل, ولكن جدير بالذكر ان البرنامج يعمل بدون مشاكل في جهازي الذي يعمل بنظام ويندوز 10 وحتى على VoidLinux لم تواجهني اي مشاكل والبرنامج يعمل كالمتوقع.

**سوف اناقش موضوع عمل refactor كامل للمشروع من الصفر مع @rn0x المؤسس للمشروع بحيث نعيد ترتيب وكتابة الأكواد وعمل فحص شامل لها لإصدار تحديث مستقر باذن الله ولاننسى التحديث للإصدار الجديد من electronjs.**

![Screenshot 2023-02-25 1504223](https://user-images.githubusercontent.com/52936496/221358459-a579fc06-4d3d-454a-8048-4561d1433b7c.png)
<br>
![Screenshot 2023-02-25 150422](https://user-images.githubusercontent.com/52936496/221358481-75c36342-04ff-4f06-bd0d-fe83fc63de95.png)
<br>
وشكرا على تعاونك اخي هشام وعلى المحتوى الذي تقوم بتقديمه في اليوتيوب 🤗❤ @HishamAHai .

**Comment by kemzops** [comment]
وبالنسبة لجزئية فلاتباك ف للأسف برنامج التقوى لايدعم فلاتباك بشكل كامل حاليا.

**Comment by HishamAHai** [comment]
> بسبب التحديثات المستمرة على البكجات(الملحقات) المستخدمة في المشروع والتي نعتمد عليها لايوجد تحديث مستقر بالكامل ولايمكن ضمان ذلك في الوقت الحالي... سوف اقوم بعمل تجارب عديدة على البرنامج والتحقق من وجود مشاكل, ولكن جدير بالذكر ان البرنامج يعمل بدون مشاكل في جهازي الذي يعمل بنظام ويندوز 10 وحتى على VoidLinux لم تواجهني اي مشاكل والبرنامج يعمل كالمتوقع.
> 
> **سوف اناقش موضوع عمل refactor كامل للمشروع من الصفر مع @rn0x المؤسس للمشروع بحيث نعيد ترتيب وكتابة الأكواد وعمل فحص شامل لها لإصدار تحديث مستقر باذن الله ولاننسى التحديث للإصدار الجديد من electronjs.**
> 
> ![Screenshot 2023-02-25 1504223](https://user-images.githubusercontent.com/52936496/221358459-a579fc06-4d3d-454a-8048-4561d1433b7c.png) ![Screenshot 2023-02-25 150422](https://user-images.githubusercontent.com/52936496/221358481-75c36342-04ff-4f06-bd0d-fe83fc63de95.png) وشكرا على تعاونك اخي هشام وعلى المحتوى الذي تقوم بتقديمه في اليوتيوب hugsheart @HishamAHai .

بارك الله فيك يا غالي
جربت تثبيت ملف rpm على فيدورا و نسخة appimage و نفس المشكلة
لكن من الترمينال حصلت على الخطأ التالي قد يساعد على تحديد المشكلة
FetchError: request to http://ip-api.com/json failed, reason: connect ECONNREFUSED 0.0.0.0:80
    at ClientRequest.<anonymous> (/opt/Altaqwaa/resources/app.asar/node_modules/node-fetch/lib/index.js:1505:11)

**Comment by HishamAHai** [comment]
هذا الخطأ بالكامل عند استخدام appimage
```
FetchError: request to http://ip-api.com/json failed, reason: connect ECONNREFUSED 0.0.0.0:80
    at ClientRequest.<anonymous> (/tmp/.mount_Altaqwx5Mtb5/resources/app.asar/node_modules/node-fetch/lib/index.js:1505:11)
    at ClientRequest.emit (node:events:527:28)
    at Socket.socketErrorListener (node:_http_client:454:9)
    at Socket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}
```

**Comment by kemzops** [comment]
هل يمكنك التوجه الى http://ip-api.com/json باستخدام المتصفح وعرض البيانات الموجودة في تلك الصفحة ؟ او على الأقل يجب ان تكون كالتالي: 
```json
{"status":"success","country":"Palestinian Territory","countryCode":"PS","region":"","regionName":"West Bank","city":"Nablus","zip":"","lat":32.2211,"lon":35.2544,"timezone":"Asia/Hebron","isp":"Hadara BSA Gaza","org":"","as":"AS12975 Palestine Telecommunications Company (PALTEL)","query":"XX.X.XXX.XXX"}
```
والتي تستخدم لتحديد موقعك الجغرافي لمساعدتك على اعداد مواقيت الصلاة بسهولة.

**Comment by HishamAHai** [comment]
يبدو أن المشكلة عندي مرتبطة مباشرة بإعدادات الشبكة في البيت و العمل.لإني ضابطها بشكل أن لا تقبل أي إنصالات غير مشفرة يعني http لا يتصل
بالبيت ممكن إني عدل الإعدادات مع إني أفضل الاتصالات المشفرة لكن في العمل فما باليد حيلة 
رح أحاول غير الإعدادات و إنشاء الله تعمل
شكراً على طيبة قلبك

**Comment by kemzops** [comment]
> هذا الخطأ بالكامل عند استخدام appimage
> 
> ```
> FetchError: request to http://ip-api.com/json failed, reason: connect ECONNREFUSED 0.0.0.0:80
>     at ClientRequest.<anonymous> (/tmp/.mount_Altaqwx5Mtb5/resources/app.asar/node_modules/node-fetch/lib/index.js:1505:11)
>     at ClientRequest.emit (node:events:527:28)
>     at Socket.socketErrorListener (node:_http_client:454:9)
>     at Socket.emit (node:events:527:28)
>     at emitErrorNT (node:internal/streams/destroy:157:8)
>     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
>     at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
>   type: 'system',
>   errno: 'ECONNREFUSED',
>   code: 'ECONNREFUSED'
> }
> ```

يبدو ان هنالك شيء يمنع node-fetch من عمل GET Request لـ API `http://ip-api.com/json`
يبدو انها مشكلة متعلقة بالجدار الناري او ما شابه

**Comment by kemzops** [comment]
> يبدو أن المشكلة عندي مرتبطة مباشرة بإعدادات الشبكة في البيت و العمل.لإني ضابطها بشكل أن لا تقبل أي إنصالات غير مشفرة يعني http لا يتصل بالبيت ممكن إني عدل الإعدادات مع إني أفضل الاتصالات المشفرة لكن في العمل فما باليد حيلة رح أحاول غير الإعدادات و إنشاء الله تعمل شكراً على طيبة قلبك

نعم صحيح سبب استخدام HTTP بدلا عن HTTP/S
هو طلب مزودي الخدمة بالإشتراك Pro الذي يكلف ما يقارب 14 يورو للحصول على SSL وبالتالي استخدام HTTP/S وبالطبع لمشروع مجاني ومفتوح المصدر وبدون اي دخل ثابت ذلك مستحيل.

`https://members.ip-api.com/#pricing`

وشكرا لك اخي الكريم ❤.

**Comment by HishamAHai** [comment]
كانت المشكلة في البيت من pihole عملت whitelist للرابط و اشتغل 🎉🎉🎉

**Comment by HishamAHai** [comment]
ممكن اقترح إضافة بعض الميزات في الإصدارات القادمة:
* إضافة خيار لتغيير المقطع الصوتي للأذان
* إضافة flag عند تشغيل البرنامج من الترمينال لجعله مخفياً بشكل أوتوماتيكي عند تشغيل البرنامج مع بقاءه يعمل في الخلفية مثلاً
```
altaqwa --no-gui
```

**Comment by kemzops** [comment]
> ممكن اقترح إضافة بعض الميزات في الإصدارات القادمة:
> 
> * إضافة خيار لتغيير المقطع الصوتي للأذان
> * إضافة flag عند تشغيل البرنامج من الترمينال لجعله مخفياً بشكل أوتوماتيكي عند تشغيل البرنامج مع بقاءه يعمل في الخلفية مثلاً
> 
> ```
> altaqwa --no-gui
> ```

شكرا لك على الإقتراح الأول بأذن الله سوف نعمل عليه اما الإقتراح الثاني ف من الممكن عمل مشروع آخر منفصل بحيث يكون `altaqwaa-cli`
ولكن لا انصح بالإنتقال الى مشاريع اخرى والمشروع الرئيسي بحاجة الى عمل ليكون مستقر وكامل الميزات...

**Comment by kemzops** [comment]
@rn0x close issue
